language: python # => 1
       
python: # => 2
  - "3.8.5"
services: => 3
  - db.sqlite3
env: # => 4
  - DJANGO=3.1.1 DB=db.sqlite3
install: # => 5
  - pip install -r requirements.txt
before_script: # => 6
  - db.sqlite3 -e 'create database test;' -u root
script: # => 7
  - python manage.py test

