language: python # => 1
       
python: # => 2
  - "3.8.5"
  - "3.6"
  - "3.7"
cache: pip
services: => 3
  - sqlite3
env: # => 4
  - DJANGO=3.1.1 DB=sqlite3
install: # => 5
  - pip install -r requirements.txt
before_script: 
  - sqlite3  - e 'create database test;' -u root
script: # => 7
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
  

