# Generated by Django 3.1.2 on 2020-10-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevercipeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='image',
            field=models.ImageField(blank=True, max_length=144, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
