# Generated by Django 3.1.2 on 2020-11-01 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RevercipeApp', '0003_recipemodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='author',
        ),
    ]
