# Generated by Django 3.1.2 on 2020-11-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RevercipeApp', '0004_remove_recipemodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='comments',
        ),
    ]
