# Generated by Django 3.1.2 on 2020-11-01 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RevercipeApp', '0005_remove_userprofilemodel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RevercipeApp.comment'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='pantry_ingredients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RevercipeApp.ingredientmodel'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='recipes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RevercipeApp.recipemodel'),
        ),
    ]
