# Generated by Django 3.1.2 on 2020-11-01 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RevercipeApp', '0008_auto_20201101_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
