# Generated by Django 3.1.2 on 2020-11-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevercipeApp', '0010_userprofilemodel_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='avatar',
            field=models.ImageField(blank=True, max_length=144, null=True, upload_to='uploads/profile/'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='image',
            field=models.ImageField(blank=True, max_length=144, null=True, upload_to='uploads/recipes/'),
        ),
    ]
