# Generated by Django 3.1.2 on 2020-11-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevercipeApp', '0011_auto_20201114_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='avatar',
            field=models.ImageField(default='/static/images/default.png', max_length=144, upload_to='uploads/profile/'),
        ),
    ]
