# Generated by Django 3.1.2 on 2020-11-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevercipeApp', '0014_auto_20201116_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorite',
            field=models.IntegerField(default=1),
        ),
    ]
