# Generated by Django 3.1.2 on 2020-11-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevercipeApp', '0016_auto_20201116_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientmodel',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingredientmodel',
            name='amount_type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
