# Generated by Django 3.1.2 on 2020-11-16 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RevercipeApp', '0017_auto_20201116_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RevercipeApp.recipemodel'),
        ),
    ]
