# Generated by Django 3.1.2 on 2020-11-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RevercipeApp', '0020_userprofilemodel_follow_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='follow_count',
            new_name='favorite_count',
        ),
    ]
