# Generated by Django 3.1.2 on 2020-11-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevercipeApp', '0021_auto_20201130_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
    ]
