# Generated by Django 3.1.2 on 2020-12-08 01:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RevercipeApp', '0024_auto_20201208_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 1, 53, 3, 244499, tzinfo=utc)),
        ),
    ]
