# Generated by Django 3.1.2 on 2020-12-09 05:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RevercipeApp', '0025_auto_20201208_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 5, 9, 29, 894254, tzinfo=utc)),
        ),
    ]
